# Generated by Django 5.2.17 on 2026-08-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='movie_collections.collection')),
            ],
        ),
    ]
